// <auto-generated />
using System;
using InformationCollector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformationCollector.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InformationCollector.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Dhaka",
                            CountryID = 1
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Mymensingh",
                            CountryID = 1
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Sylhet",
                            CountryID = 1
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Jeddah",
                            CountryID = 2
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Mumbai",
                            CountryID = 3
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Dilhi",
                            CountryID = 3
                        });
                });

            modelBuilder.Entity("InformationCollector.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "India"
                        });
                });

            modelBuilder.Entity("InformationCollector.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageName = "C#"
                        },
                        new
                        {
                            Id = 2,
                            LanguageName = "Angualar"
                        },
                        new
                        {
                            Id = 3,
                            LanguageName = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            LanguageName = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            LanguageName = "C"
                        },
                        new
                        {
                            Id = 6,
                            LanguageName = "Java"
                        });
                });

            modelBuilder.Entity("InformationCollector.Models.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Informations");
                });

            modelBuilder.Entity("InformationCollector.Models.LanguageDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("InformationId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InformationId");

                    b.ToTable("LanguageDTO");
                });

            modelBuilder.Entity("InformationCollector.Models.LanguageDTO", b =>
                {
                    b.HasOne("InformationCollector.Models.Information", null)
                        .WithMany("Language")
                        .HasForeignKey("InformationId");
                });

            modelBuilder.Entity("InformationCollector.Models.Information", b =>
                {
                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
