// <auto-generated />
using InformationCollector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformationCollector.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InformationCollector.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Dhaka",
                            CountryID = 1
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Mymensingh",
                            CountryID = 1
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Sylhet",
                            CountryID = 1
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Jeddah",
                            CountryID = 2
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Mumbai",
                            CountryID = 3
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Dilhi",
                            CountryID = 3
                        });
                });

            modelBuilder.Entity("InformationCollector.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "India"
                        });
                });

            modelBuilder.Entity("InformationCollector.Models.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Informations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Dhaka",
                            Country = "BD",
                            DateOfBirth = "2000-11-01",
                            Language = "C#, Javascipt, HTML, CSS",
                            Name = "Md. Mahfuzullah",
                            ResumeUrl = "resume/Resume of Mahfuzullah.pdf"
                        },
                        new
                        {
                            Id = 2,
                            City = "Jessure",
                            Country = "JS",
                            DateOfBirth = "1999-03-26",
                            Language = "C#, Javascipt, HTML, CSS",
                            Name = "Asif",
                            ResumeUrl = "resume/Asif Hasan Resume.pdf"
                        },
                        new
                        {
                            Id = 3,
                            City = "Dhaka",
                            Country = "BD",
                            DateOfBirth = "2000-11-01",
                            Language = "C#, Javascipt, HTML, CSS",
                            Name = "Md. Mahfuzullah",
                            ResumeUrl = "resume/Resume of Mahfuzullah.pdf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
